### ISSUE TITLE
Moodle doesn't connect with Mahara

### ISSUE THREAD

**Issue by Kfnig24** [catalyst/moodle-assignsubmission_maharaws#63] opened 2023-08-23 08:05 UTC
# Hello ✋🏼 

### I am trying to connect my Moodle installation with Mahara but each time it try to connect, Moodle returns this error : 

<img width="1916" alt="Screenshot 2023-08-23 at 09 16 33" src="https://github.com/catalyst/moodle-assignsubmission_maharaws/assets/60477500/df0f4c70-1216-4013-a46c-d1f6f3a0116e">
I checked the url and the API keys many times and I'm sure there are valid.

Both of the apps run on docker, but I don't think it's the problem as I tried with installations on my local computer. However, when I looked into the docker logs, mahara doesn't received any requests from moodle:

<img width="1320" alt="image" src="https://github.com/catalyst/moodle-assignsubmission_maharaws/assets/60477500/c147156b-3b40-41ba-8c19-f9c3d0c33cc7">
Mahara logs(I ran the request at 09:24)

<img width="1288" alt="image" src="https://github.com/catalyst/moodle-assignsubmission_maharaws/assets/60477500/b53ac92b-dfbe-4c01-96cf-fc5cdd647323">
Moodle logs

### Here is the config for the plugin:
URL: http://host.docker.internal:6142/mahara-docker2-81/
Screenshot: 
<img width="1870" alt="image" src="https://github.com/catalyst/moodle-assignsubmission_maharaws/assets/60477500/caefd2fa-3f3c-48fe-93b4-5db48d89a13d">

### For the url, here is a test request sent from the moodle container:
<img width="1299" alt="image" src="https://github.com/catalyst/moodle-assignsubmission_maharaws/assets/60477500/16b69757-d8f6-4e47-810b-761315815fe9">

Thanks !

**Comment by danmarsden** [comment] 2023-08-24 02:21
Moodle will block the 6142 port by default - so make sure that's an allowed port in the Moodle curl security settings on your site, also I'm not sure we've tested this on a non-https site - it should really be doing this on an https public url so that you can make sure the Moodle site can actually see the Mahara site (note the communication happens via the back-channel server to server rather than through your browser session, so the servers must be able to see each other and access each other via the ports you have defined there.)
if the mahara server is not even getting to the site it's probably a firewall related or dns issue though - try opening up the cli on the Moodle server and do a cli based curl call to see if it can acces the mahara site.

Also - if you're using Apache as your webserver - check out the readme for an issue with the headers. (but that doesn't appear to be your current issue if the mahara access log isn't even showing a call.)

I'm closing this as "not a bug" as it definitely appears to be a communications/configuration issue at this stage. If you have an enterprise Subscription for Mahara, feel free to reach out and log an issue via your subscription if you would like further help.

thanks!

**Closed by danmarsden** 2023-08-24 02:21 UTC
