### ISSUE TITLE
Failure to delete course due to issue with Mahara plugin triggering bug in Core Moodle code.

### ISSUE THREAD

**Issue by james-pearce-bath-ac** [catalyst/moodle-assignsubmission_maharaws#60] opened 2023-07-27 15:32 UTC
As per bug [MDL-75124](https://tracker.moodle.org/browse/MDL-75124), it is possible for a course_module to not be included in the sequence list for any section in the course.

If the following situation is encountered:
- An assign module is in the course
- The assign module is not in the sequence for any section of the course.
- The Mahara WS Assign Submission plugin is installed

Then when you attempt to delete the course, it fails. This is because assign_submission_maharaws->delete_instance() is calling assign->get_instance(), which as per bug [MDL-78840](https://tracker.moodle.org/browse/MDL-78840), fails with an exception.

This fails even if the assign module does not contain an assign_submission_maharaws plugin instance.

**Comment by danmarsden** [comment] 2023-08-01 07:45
Hi @james-pearce-bath-ac thanks for the report, I've had a look at this and I think the right place to report this is in the moodle core tracker which you have done already - the mahara plugin uses the same sort of lookups as the core onlinetext and file submission plugins ($this->assignment->get_instance()->id) - and if that value doesn't exist, it's probably correct to cause an exception and stop trying to delete the course otherwise orphaned data will be left in place within the database.

I suspect you should be able to reproduce this same issue within the core Moodle submission types and if you'd like to see this fixed in core moodle it might be worth trying that and updating your tracker issue to make it clear. 

I'm closing this as "not a bug" with the maharaws plugin for now, but feel free to let us know if you think that's incorrect or I've misunderstood something and we can try to take another look!

thanks!

**Closed by danmarsden** 2023-08-01 07:45 UTC

**Comment by james-pearce-bath-ac** [comment] 2023-08-01 10:05
Thanks @danmarsden, we've confirmed it does break with the standard assignment submission plugins as well. We are updating the tracker ticket accordingly.
